name: Deploy to EC2

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install backend dependencies
      run: npm install
      
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build Angular app
      run: |
        cd frontend
        npm run build
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /var/www/formbuilder
          git pull origin main
          npm install --production
          cd frontend
          npm install
          npm run build
          cd ..
          
          # Update environment variables
          echo "PORT=3000" > .env
          echo "NODE_ENV=production" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}" >> .env
          echo "JWT_EXPIRE=15m" >> .env
          echo "JWT_REFRESH_EXPIRE=7d" >> .env
          
          # Restart application
          pm2 restart formbuilder-app || pm2 start server.js --name "formbuilder-app"
          pm2 save
          
          # Reload nginx
          sudo systemctl reload nginx